[[redirects]]
  from = "/api/*"
  to = "https://API_DOMAIN_PLACEHOLDER/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [redirects.headers]
    Pragma = "no-cache"
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

[build]
  command = "sed -i \"s|API_DOMAIN_PLACEHOLDER|${API_DOMAIN}|g\" netlify.toml && npm run build"
  environment = { CI = "false" }

