[[redirects]]
  from = "/api/*"
  to = "https://wav-game-staging.liquality.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [redirects.headers]
    Pragma = "no-cache"
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
