/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { WavGame__factory } from "./WavGame__factory";
export { WavNFT__factory } from "./WavNFT__factory";
