/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWavGame,
  IWavGameInterface,
} from "../../../contracts/interfaces/IWavGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_artistID",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "collect",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "forwardValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_artistID",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_newLevelID",
        type: "uint256",
      },
    ],
    name: "levelUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_artistID",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "requiredBurn",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "requiredMint",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "earlyBirdCutOff",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "mintID",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "burnID",
            type: "uint256",
          },
        ],
        internalType: "struct IWavGame.LevelParam[]",
        name: "_levels",
        type: "tuple[]",
      },
    ],
    name: "setArtistGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_feePerMint",
        type: "uint256",
      },
    ],
    name: "setFeePerMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_artistIDs",
        type: "uint256[]",
      },
      {
        internalType: "address payable[]",
        name: "_treasuries",
        type: "address[]",
      },
    ],
    name: "setTreasuries",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferWavNftOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_artistID",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_levelID",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "requiredBurn",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "requiredMint",
            type: "uint8",
          },
          {
            internalType: "uint32",
            name: "earlyBirdCutOff",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "mintID",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "burnID",
            type: "uint256",
          },
        ],
        internalType: "struct IWavGame.LevelParam",
        name: "_levelParam",
        type: "tuple",
      },
    ],
    name: "updateLevel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_artistID",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_levelID",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "wavMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWavGame__factory {
  static readonly abi = _abi;
  static createInterface(): IWavGameInterface {
    return new utils.Interface(_abi) as IWavGameInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWavGame {
    return new Contract(address, _abi, signerOrProvider) as IWavGame;
  }
}
