/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iWavNftSol from "./IWavNFT.sol";
export type { iWavNftSol };
export type { IWavGame } from "./IWavGame";
